/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package architecture;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Adrian
 */
    public class JPanel_lab_11_2 extends javax.swing.JPanel {   

        public JPanel_lab_11_2() {
        initComponents();

        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Dialogs Demo");
            frame.setSize(400, 300);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            JButton messageDialogButton = new JButton("Show Message Dialog");
            messageDialogButton.addActionListener(e -> {
                JOptionPane.showMessageDialog(frame, "This is a Message Dialog", "Message", JOptionPane.INFORMATION_MESSAGE);
            });

            JButton inputDialogButton = new JButton("Show Input Dialog");
            inputDialogButton.addActionListener(e -> {
                String userInput = JOptionPane.showInputDialog(frame, "Enter your name:");
                if (userInput != null) {
                    JOptionPane.showMessageDialog(frame, "Hello, " + userInput + "!");
                }
            });

            JPanel panel = new JPanel();
            panel.setLayout(new GridLayout(2, 1));
            panel.add(messageDialogButton);
            panel.add(inputDialogButton);

            frame.getContentPane().add(panel);
            frame.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
