/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package architecture;

import javax.swing.*;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Adrian
 */
public class JPanel_lab_11_1 extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_lab_11
     */
    public JPanel_lab_11_1() {
        initComponents();
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Simple Test");
            frame.setSize(400, 300);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            String[] answers = {"Option 1", "Option 2", "Option 3", "Option 4"};
            JList<String> answerList = new JList<>(answers);

            JButton submitButton = new JButton("Submit");
            submitButton.addActionListener(new ActionListenerImpl(frame, answerList));

            JPanel panel = new JPanel();
            panel.add(new JLabel("Select your answer:"));
            panel.add(answerList);
            panel.add(submitButton);

            frame.getContentPane().add(panel);
            frame.setVisible(true);
        });  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    void pack() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private static class ActionListenerImpl implements ActionListener {

        private final JFrame frame;
        private final JList<String> answerList;

        public ActionListenerImpl(JFrame frame, JList<String> answerList) {
            this.frame = frame;
            this.answerList = answerList;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            JOptionPane.showMessageDialog(frame, "Selected Answer: " + answerList.getSelectedValue());
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
